// Entry type definition
interface WeightliftingEntry { 
    name: string; 
    club: string;
    weightCategory: string; 
    entryTotal: string; 
}

// Scraped entries data
export const entries: WeightliftingEntry[] = [
{ name: "Makayla Compton", club: "Warner University", weightCategory: "Female 45kg", entryTotal: "80" },
{ name: "Christina Rameau", club: "Gator Weightlifting", weightCategory: "Female 45kg", entryTotal: "85" },
{ name: "Lilly Cottingham", club: "FORZA WEIGHTLIFTING CLUB", weightCategory: "Female 45kg", entryTotal: "90" },
{ name: "Ashley Cucchiara", club: "Gator Weightlifting", weightCategory: "Female 45kg", entryTotal: "90" },
{ name: "Delaney Bollman", club: "CROSSFIT FORT VANCOUVER BARBELL CLUB", weightCategory: "Female 45kg", entryTotal: "100" },
{ name: "Mikayla Tijunait", club: "ONG WEIGHTLIFTING", weightCategory: "Female 49kg", entryTotal: "84" },
{ name: "Madhumati Mirel", club: "Unaffiliated", weightCategory: "Female 49kg", entryTotal: "95" },
{ name: "Tristan Kiyan", club: "University of Oregon Weightlifting Club", weightCategory: "Female 49kg", entryTotal: "103" },
{ name: "Nina Mergen", club: "Team Minnesota", weightCategory: "Female 49kg", entryTotal: "105" },
{ name: "Xitlalic Montelongo", club: "Orlando Strength", weightCategory: "Female 49kg", entryTotal: "105" },
{ name: "Makayla Gilbert", club: "FSU Weightlifting", weightCategory: "Female 49kg", entryTotal: "115" },
{ name: "Kaitlin Lacey", club: "Gator Weightlifting", weightCategory: "Female 49kg", entryTotal: "130" },
{ name: "Reagan Best", club: "Mars Hill University", weightCategory: "Female 49kg", entryTotal: "134" },
{ name: "Amanda Serapiglia", club: "EAST COAST GOLD W/L TEAM", weightCategory: "Female 49kg", entryTotal: "136" },
{ name: "Amaya Carricaburu", club: "University of Oregon Weightlifting Club", weightCategory: "Female 55kg", entryTotal: "93" },
{ name: "Anna Sophocleous", club: "Gator Weightlifting", weightCategory: "Female 55kg", entryTotal: "98" },
{ name: "Neena Schramm", club: "Gator Weightlifting", weightCategory: "Female 55kg", entryTotal: "102" },
{ name: "Addison Seay", club: "Unaffiliated", weightCategory: "Female 55kg", entryTotal: "102" },
{ name: "Erin Troiano", club: "UVM Weightlifting Club", weightCategory: "Female 55kg", entryTotal: "103" },
{ name: "Jaiden Avila", club: "ATU Lifting Club", weightCategory: "Female 55kg", entryTotal: "108" },
{ name: "Ashley Aun", club: "Gator Weightlifting", weightCategory: "Female 55kg", entryTotal: "114" },
{ name: "Dalana Smith", club: "Beyond The Barbell", weightCategory: "Female 55kg", entryTotal: "115" },
{ name: "mackenzie houser", club: "Concordia University Weightlifting", weightCategory: "Female 55kg", entryTotal: "118" },
{ name: "Julia Azzopardi", club: "Team Florida Gainesville", weightCategory: "Female 55kg", entryTotal: "120" },
{ name: "Aimee Causby", club: "HARRISBURG WEIGHTLIFTING CLUB", weightCategory: "Female 55kg", entryTotal: "137" },
{ name: "Desiray Green", club: "Unaffiliated", weightCategory: "Female 55kg", entryTotal: "140" },
{ name: "Madi Muse", club: "Mars Hill University", weightCategory: "Female 55kg", entryTotal: "147" },
{ name: "Denise Diaz", club: "HEAVY METAL BARBELL", weightCategory: "Female 55kg", entryTotal: "150" },
{ name: "Violeta Fernandez", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Female 55kg", entryTotal: "160" },
{ name: "Callie Goolgasian", club: "Gator Weightlifting", weightCategory: "Female 55kg", entryTotal: "168" },
{ name: "Olivia Jacobs", club: "FSU Weightlifting", weightCategory: "Female 59kg", entryTotal: "105" },
{ name: "Ariana Aranda", club: "LINDENWOOD LIONS", weightCategory: "Female 59kg", entryTotal: "110" },
{ name: "Katelyn Fecteau", club: "Unaffiliated", weightCategory: "Female 59kg", entryTotal: "115" },
{ name: "Kaitlyn Gastineau", club: "University of Michigan Weightlifting", weightCategory: "Female 59kg", entryTotal: "115" },
{ name: "Chloe Gaspar", club: "Concordia University Weightlifting", weightCategory: "Female 59kg", entryTotal: "118" },
{ name: "Alena Morris", club: "PIONEER WLC", weightCategory: "Female 59kg", entryTotal: "119" },
{ name: "Laurynn Lackey", club: "Team Florida Gainesville", weightCategory: "Female 59kg", entryTotal: "119" },
{ name: "Jenna Young", club: "People's Republic of The Dojo", weightCategory: "Female 59kg", entryTotal: "120" },
{ name: "Talya DeMarco", club: "Gator Weightlifting", weightCategory: "Female 59kg", entryTotal: "120" },
{ name: "Jillian Jacobs", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Female 59kg", entryTotal: "124" },
{ name: "Karen Marumoto", club: "University of Oregon Weightlifting Club", weightCategory: "Female 59kg", entryTotal: "125" },
{ name: "Amber Bailey", club: "LINDENWOOD LIONS", weightCategory: "Female 59kg", entryTotal: "130" },
{ name: "Delaney Cookman", club: "Gator Weightlifting", weightCategory: "Female 59kg", entryTotal: "133" },
{ name: "Ariel Hekier", club: "ATHLETIC LAB WLC", weightCategory: "Female 59kg", entryTotal: "135" },
{ name: "Hannah Stgerard", club: "LSU - Shreveport", weightCategory: "Female 59kg", entryTotal: "139" },
{ name: "Grace Gonzalez-Liz", club: "LSU - Shreveport", weightCategory: "Female 59kg", entryTotal: "142" },
{ name: "Katherine Greisdorf", club: "BEANTOWN BARBELL CLUB", weightCategory: "Female 59kg", entryTotal: "145" },
{ name: "Karman Holley", club: "FSU Weightlifting", weightCategory: "Female 59kg", entryTotal: "149" },
{ name: "Lexi Pepper", club: "BlueWave Weightlifting", weightCategory: "Female 59kg", entryTotal: "150" },
{ name: "Alyssa Jordan", club: "Mars Hill University", weightCategory: "Female 59kg", entryTotal: "150" },
{ name: "Taylor Hedke", club: "Concordia University Weightlifting", weightCategory: "Female 59kg", entryTotal: "154" },
{ name: "Zoe Pasetsky", club: "Bexar Barbell", weightCategory: "Female 59kg", entryTotal: "160" },
{ name: "Alexa Estevez", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Female 59kg", entryTotal: "165" },
{ name: "Eden hansen", club: "TEXAS BARBELL CLUB", weightCategory: "Female 59kg", entryTotal: "165" },
{ name: "Susanna Eng", club: "West Coast Weightlifting", weightCategory: "Female 64kg", entryTotal: "112" },
{ name: "Kinali Patel", club: "Unaffiliated", weightCategory: "Female 64kg", entryTotal: "120" },
{ name: "Emily Varga", club: "Jacksonville Weightlifting", weightCategory: "Female 64kg", entryTotal: "121" },
{ name: "Mia Mohr", club: "Unaffiliated", weightCategory: "Female 64kg", entryTotal: "121" },
{ name: "Jalyssa Robinson", club: "Warner University", weightCategory: "Female 64kg", entryTotal: "123" },
{ name: "Jordan Bruce", club: "West Tennessee Weightlifting", weightCategory: "Female 64kg", entryTotal: "125" },
{ name: "Haley Headrick", club: "Emory University Weightlifting Club", weightCategory: "Female 64kg", entryTotal: "128" },
{ name: "Melody Rodriguez", club: "Unaffiliated", weightCategory: "Female 64kg", entryTotal: "130" },
{ name: "McKenzie Bieg", club: "SAS WEIGHTLIFTING CLUB", weightCategory: "Female 64kg", entryTotal: "130" },
{ name: "Yamariz Perez", club: "Gator Weightlifting", weightCategory: "Female 64kg", entryTotal: "130" },
{ name: "Karla Ramon", club: "University of Michigan Weightlifting", weightCategory: "Female 64kg", entryTotal: "131" },
{ name: "HarleyJane Carter", club: "Concordia University Weightlifting", weightCategory: "Female 64kg", entryTotal: "135" },
{ name: "Jordyn Dearth", club: "LINDENWOOD LIONS", weightCategory: "Female 64kg", entryTotal: "137" },
{ name: "Lindsey Chappell", club: "Jacksonville Weightlifting", weightCategory: "Female 64kg", entryTotal: "140" },
{ name: "Devin Craig-Schwartz", club: "Lupo Barbell Club", weightCategory: "Female 64kg", entryTotal: "140" },
{ name: "Cassie McClure", club: "Bobcat Barbell", weightCategory: "Female 64kg", entryTotal: "141" },
{ name: "Marlow Nichols", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Female 64kg", entryTotal: "145" },
{ name: "Sophie Desatnik", club: "Olympic Weightlifting Club at The Ohio State University", weightCategory: "Female 64kg", entryTotal: "148" },
{ name: "Gabrielle Lerner", club: "Gator Weightlifting", weightCategory: "Female 64kg", entryTotal: "150" },
{ name: "Elle Hatamiya", club: "Team Aita", weightCategory: "Female 64kg", entryTotal: "152" },
{ name: "Alexa Woodman", club: "Orlando Strength", weightCategory: "Female 64kg", entryTotal: "160" },
{ name: "Ava Oteri", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Female 64kg", entryTotal: "165" },
{ name: "Laura Cochran", club: "LINDENWOOD LIONS", weightCategory: "Female 64kg", entryTotal: "179" },
{ name: "Makiyah Nickerson", club: "Mars Hill University", weightCategory: "Female 64kg", entryTotal: "185" },
{ name: "Brie Gomez", club: "UNIVERSITY OF TEXAS", weightCategory: "Female 64kg", entryTotal: "185" },
{ name: "Elizabeth Colwell", club: "Unaffiliated", weightCategory: "Female 71kg", entryTotal: "0" },
{ name: "Rilee Whitmore", club: "FSU Weightlifting", weightCategory: "Female 71kg", entryTotal: "111" },
{ name: "Juliann Will", club: "UW - LA CROSSE WEIGHTLIFTING CLUB", weightCategory: "Female 71kg", entryTotal: "125" },
{ name: "Brittney Chang", club: "Gator Weightlifting", weightCategory: "Female 71kg", entryTotal: "125" },
{ name: "Leigha Sutton", club: "FSU Weightlifting", weightCategory: "Female 71kg", entryTotal: "125" },
{ name: "Johanna Hernandez", club: "Warner University", weightCategory: "Female 71kg", entryTotal: "125" },
{ name: "Sofia Northrup", club: "Gator Weightlifting", weightCategory: "Female 71kg", entryTotal: "126" },
{ name: "Camille Lafferty", club: "CLEAN SLATE WEIGHTLIFTING", weightCategory: "Female 71kg", entryTotal: "126" },
{ name: "Paige White", club: "PIONEER WLC", weightCategory: "Female 71kg", entryTotal: "127" },
{ name: "Abigail Goldman", club: "Unaffiliated", weightCategory: "Female 71kg", entryTotal: "130" },
{ name: "Jordyn Craig-Schwartz", club: "Lupo Barbell Club", weightCategory: "Female 71kg", entryTotal: "132" },
{ name: "Gabby Greene", club: "ONG WEIGHTLIFTING", weightCategory: "Female 71kg", entryTotal: "135" },
{ name: "Ameli Patrick", club: "Unaffiliated", weightCategory: "Female 71kg", entryTotal: "135" },
{ name: "Nancy Mahmoud", club: "UC-Santa Barbara", weightCategory: "Female 71kg", entryTotal: "140" },
{ name: "Leslie Liu", club: "UC-Santa Barbara", weightCategory: "Female 71kg", entryTotal: "140" },
{ name: "Alma Lopez", club: "Texas A&M Aggie Weightlifting", weightCategory: "Female 71kg", entryTotal: "140" },
{ name: "Shelby Miller", club: "Bujanda Strong", weightCategory: "Female 71kg", entryTotal: "140" },
{ name: "Summer de la Cruz", club: "FORZA WEIGHTLIFTING CLUB", weightCategory: "Female 71kg", entryTotal: "142" },
{ name: "Tiana Bowers", club: "Orlando Strength", weightCategory: "Female 71kg", entryTotal: "143" },
{ name: "Reese Hayward", club: "Hammer Strength WLC", weightCategory: "Female 71kg", entryTotal: "145" },
{ name: "Kela Kauhaahaa", club: "LSU - Shreveport", weightCategory: "Female 71kg", entryTotal: "152" },
{ name: "Halie Thornton", club: "Fourteen Forty Collective", weightCategory: "Female 71kg", entryTotal: "155" },
{ name: "Robin Witt", club: "MILWAUKEE BARBELL WEIGHTLIFTING CLUB", weightCategory: "Female 71kg", entryTotal: "155" },
{ name: "Victoria Carter", club: "Iowa Elite", weightCategory: "Female 71kg", entryTotal: "156" },
{ name: "Nina Pollack", club: "Concordia University Weightlifting", weightCategory: "Female 71kg", entryTotal: "158" },
{ name: "Gracy Johnson", club: "Concordia University Weightlifting", weightCategory: "Female 71kg", entryTotal: "160" },
{ name: "Kaitlyn sheppard", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Female 71kg", entryTotal: "160" },
{ name: "Hattie Johnson", club: "Gator Weightlifting", weightCategory: "Female 71kg", entryTotal: "160" },
{ name: "Linda Buitron", club: "Valhalla Weightlifting", weightCategory: "Female 71kg", entryTotal: "160" },
{ name: "Addison Clayton", club: "LINDENWOOD LIONS", weightCategory: "Female 71kg", entryTotal: "160" },
{ name: "Lillian Spry", club: "LINDENWOOD LIONS", weightCategory: "Female 71kg", entryTotal: "160" },
{ name: "Amelia Kushner", club: "UNIVERSITY OF TEXAS", weightCategory: "Female 71kg", entryTotal: "161" },
{ name: "Adriana Ufferman", club: "Optimus Barbell Club", weightCategory: "Female 71kg", entryTotal: "163" },
{ name: "Ivy Gunn", club: "Mars Hill University", weightCategory: "Female 71kg", entryTotal: "171" },
{ name: "Allison Ambler", club: "Fourteen Forty Collective", weightCategory: "Female 71kg", entryTotal: "175" },
{ name: "Autumn Szucs", club: "CFC Weightlifting Club", weightCategory: "Female 71kg", entryTotal: "180" },
{ name: "Patricia Eliscupides", club: "HOOSIER BARBELL CLUB", weightCategory: "Female 71kg", entryTotal: "180" },
{ name: "haley trinh", club: "HASSLE FREE BBC", weightCategory: "Female 71kg", entryTotal: "190" },
{ name: "Addie Anderson", club: "Zion Barbell", weightCategory: "Female 71kg", entryTotal: "200" },
{ name: "Elissa Mueller", club: "Unaffiliated", weightCategory: "Female 76kg", entryTotal: "129" },
{ name: "taylor deBritto", club: "Orlando Strength", weightCategory: "Female 76kg", entryTotal: "129" },
{ name: "Sophia Miller", club: "Unaffiliated", weightCategory: "Female 76kg", entryTotal: "132" },
{ name: "Tyra Sulph", club: "Orlando Strength", weightCategory: "Female 76kg", entryTotal: "140" },
{ name: "Charlize Viola", club: "POWER AND GRACE PERFORMANCE.", weightCategory: "Female 76kg", entryTotal: "140" },
{ name: "Brianna McCullers", club: "Warner University", weightCategory: "Female 76kg", entryTotal: "140" },
{ name: "Delaney Willingham", club: "Team Florida Gainesville", weightCategory: "Female 76kg", entryTotal: "150" },
{ name: "Julia Polvino", club: "Unaffiliated", weightCategory: "Female 76kg", entryTotal: "152" },
{ name: "Riley Williams", club: "Rising Tide Weightlifting", weightCategory: "Female 76kg", entryTotal: "160" },
{ name: "Rylee Kara", club: "LINDENWOOD LIONS", weightCategory: "Female 76kg", entryTotal: "170" },
{ name: "Enyjai Tyson", club: "LSU - Shreveport", weightCategory: "Female 76kg", entryTotal: "175" },
{ name: "Alexandra Hedges", club: "Butcher Barbell", weightCategory: "Female 76kg", entryTotal: "180" },
{ name: "Ruby Shepard", club: "Unaffiliated", weightCategory: "Female 76kg", entryTotal: "192" },
{ name: "Andrea Barrows", club: "Keep Pulling", weightCategory: "Female 76kg", entryTotal: "195" },
{ name: "Grace Montgomery", club: "LINDENWOOD LIONS", weightCategory: "Female 76kg", entryTotal: "195" },
{ name: "Shay Carlock", club: "Bexar Barbell", weightCategory: "Female 76kg", entryTotal: "200" },
{ name: "Kat Carter", club: "RUBBER CITY WEIGHTLIFTING", weightCategory: "Female 76kg", entryTotal: "200" },
{ name: "Holly Lewis", club: "Unaffiliated", weightCategory: "Female 81kg", entryTotal: "125" },
{ name: "Jordan Simpson", club: "Oly Concepts", weightCategory: "Female 81kg", entryTotal: "125" },
{ name: "Chloe Varady", club: "LINDENWOOD LIONS", weightCategory: "Female 81kg", entryTotal: "130" },
{ name: "Kate Rossner", club: "UW - LA CROSSE WEIGHTLIFTING CLUB", weightCategory: "Female 81kg", entryTotal: "132" },
{ name: "Julia VanBurger", club: "Unaffiliated", weightCategory: "Female 81kg", entryTotal: "133" },
{ name: "Evelyn Ragsdale", club: "Unaffiliated", weightCategory: "Female 81kg", entryTotal: "153" },
{ name: "Allysen Byerley", club: "LINDENWOOD LIONS", weightCategory: "Female 81kg", entryTotal: "160" },
{ name: "Rubie Dobbins", club: "Mars Hill University", weightCategory: "Female 81kg", entryTotal: "165" },
{ name: "Christian Pommells", club: "Exclusive Club Weightlifting", weightCategory: "Female 81kg", entryTotal: "167" },
{ name: "Chloe Pickett", club: "Praxis Weightlifting", weightCategory: "Female 81kg", entryTotal: "167" },
{ name: "Kayden Arliss", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Female 81kg", entryTotal: "170" },
{ name: "Savannah Bolden", club: "LSU - Shreveport", weightCategory: "Female 81kg", entryTotal: "170" },
{ name: "Vanay Lyttle", club: "Gator Weightlifting", weightCategory: "Female 81kg", entryTotal: "170" },
{ name: "Michelle Ramsey", club: "Unaffiliated", weightCategory: "Female 81kg", entryTotal: "177" },
{ name: "Harley Creech", club: "HEAVY METAL BARBELL", weightCategory: "Female 81kg", entryTotal: "215" },
{ name: "Sydney Uyeda", club: "HASSLE FREE BBC", weightCategory: "Female 87kg", entryTotal: "135" },
{ name: "Linnea Schultz", club: "BLOOMINGTON-NORMAL BARBELL CLUB", weightCategory: "Female 87kg", entryTotal: "140" },
{ name: "Toni Randle", club: "Missouri Valley College Weightlifting", weightCategory: "Female 87kg", entryTotal: "140" },
{ name: "Ariana Acosta-Ramirez", club: "Mars Hill University", weightCategory: "Female 87kg", entryTotal: "147" },
{ name: "Breanna Zide", club: "HASSLE FREE BBC", weightCategory: "Female 87kg", entryTotal: "150" },
{ name: "Gianna Hagopian", club: "University of Oregon Weightlifting Club", weightCategory: "Female 87kg", entryTotal: "155" },
{ name: "Ivy Autman", club: "Keep Pulling", weightCategory: "Female 87kg", entryTotal: "168" },
{ name: "Tristain Atwood", club: "Mars Hill University", weightCategory: "Female 87kg", entryTotal: "175" },
{ name: "E’mia Jones", club: "Team Florida Gainesville", weightCategory: "Female 87kg", entryTotal: "185" },
{ name: "Jenna McClain", club: "LINDENWOOD LIONS", weightCategory: "Female 87kg", entryTotal: "189" },
{ name: "Amanda Robles", club: "HASSLE FREE BBC", weightCategory: "Female 87kg", entryTotal: "215" },
{ name: "Shayla Kanemitsu", club: "Unaffiliated", weightCategory: "Female +87kg", entryTotal: "135" },
{ name: "Michele Grelotti", club: "Unaffiliated", weightCategory: "Female +87kg", entryTotal: "140" },
{ name: "Susan Rivera", club: "Warner University", weightCategory: "Female +87kg", entryTotal: "140" },
{ name: "Madison Woodworth", club: "Missouri Valley College Weightlifting", weightCategory: "Female +87kg", entryTotal: "140" },
{ name: "Kira Barad", club: "HASSLE FREE BBC", weightCategory: "Female +87kg", entryTotal: "145" },
{ name: "Maya Moise", club: "Houston Weightlifting Academy", weightCategory: "Female +87kg", entryTotal: "147" },
{ name: "Maddie Carte", club: "Mars Hill University", weightCategory: "Female +87kg", entryTotal: "147" },
{ name: "Madisyn Hudson", club: "ATU Lifting Club", weightCategory: "Female +87kg", entryTotal: "150" },
{ name: "Josie Lawrence", club: "SAYRE PARK WLC", weightCategory: "Female +87kg", entryTotal: "160" },
{ name: "Ansley Amore", club: "HEAVY METAL BARBELL", weightCategory: "Female +87kg", entryTotal: "180" },
{ name: "Julia Yun", club: "HASSLE FREE BBC", weightCategory: "Female +87kg", entryTotal: "190" },
{ name: "Madison Atwood", club: "Mars Hill University", weightCategory: "Female +87kg", entryTotal: "196" },
{ name: "Malia Levy", club: "Praxis Weightlifting", weightCategory: "Female +87kg", entryTotal: "210" },
{ name: "Corey Morabito", club: "Missouri Valley College Weightlifting", weightCategory: "Male 55kg", entryTotal: "135" },
{ name: "Benjamen Gao", club: "Unaffiliated", weightCategory: "Male 55kg", entryTotal: "155" },
{ name: "Trevor Tanaka", club: "University of Oregon Weightlifting Club", weightCategory: "Male 55kg", entryTotal: "195" },
{ name: "Ignacio Fregoso", club: "UC-Santa Barbara", weightCategory: "Male 61kg", entryTotal: "140" },
{ name: "Lucas Silva", club: "Wormtown Weightlifting", weightCategory: "Male 61kg", entryTotal: "146" },
{ name: "Lamont Graham", club: "Warner University", weightCategory: "Male 61kg", entryTotal: "148" },
{ name: "Ishmael Foster", club: "Missouri Valley College Weightlifting", weightCategory: "Male 61kg", entryTotal: "150" },
{ name: "Jayden Harris", club: "Team Thick Weightlifting", weightCategory: "Male 61kg", entryTotal: "155" },
{ name: "Nick Lawrence", club: "Team Florida Gainesville", weightCategory: "Male 61kg", entryTotal: "175" },
{ name: "Samuel Leonard", club: "LINDENWOOD LIONS", weightCategory: "Male 61kg", entryTotal: "180" },
{ name: "Jacob Papantonakis", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male 61kg", entryTotal: "185" },
{ name: "Timo Mobley-Benoist", club: "Unaffiliated", weightCategory: "Male 61kg", entryTotal: "195" },
{ name: "Sebastian Rose", club: "HARRISBURG WEIGHTLIFTING CLUB", weightCategory: "Male 61kg", entryTotal: "200" },
{ name: "Bosco Martin", club: "Gator Weightlifting", weightCategory: "Male 61kg", entryTotal: "200" },
{ name: "Kaiden Mima", club: "Concordia University Weightlifting", weightCategory: "Male 61kg", entryTotal: "200" },
{ name: "Chase Zilcosky", club: "LINDENWOOD LIONS", weightCategory: "Male 61kg", entryTotal: "200" },
{ name: "Noel Walters", club: "Gator Weightlifting", weightCategory: "Male 61kg", entryTotal: "206" },
{ name: "Andy Lam", club: "University of Oregon Weightlifting Club", weightCategory: "Male 61kg", entryTotal: "215" },
{ name: "Samuel Deboy", club: "University of Oregon Weightlifting Club", weightCategory: "Male 67kg", entryTotal: "160" },
{ name: "Jullian Rosado", club: "Warner University", weightCategory: "Male 67kg", entryTotal: "165" },
{ name: "Connor Hwang", club: "UC-Santa Barbara", weightCategory: "Male 67kg", entryTotal: "168" },
{ name: "Jedidiah Kracl", club: "Missouri Valley College Weightlifting", weightCategory: "Male 67kg", entryTotal: "175" },
{ name: "Collin Chen", club: "Houston Weightlifting Academy", weightCategory: "Male 67kg", entryTotal: "180" },
{ name: "Jeremy Marks", club: "Gator Weightlifting", weightCategory: "Male 67kg", entryTotal: "180" },
{ name: "Luke Sterns", club: "GARAGE STRENGTH", weightCategory: "Male 67kg", entryTotal: "194" },
{ name: "Calvin Moy", club: "Texas A&M Aggie Weightlifting", weightCategory: "Male 67kg", entryTotal: "195" },
{ name: "Victor Martin", club: "Bulldog Weightlifting Club", weightCategory: "Male 67kg", entryTotal: "200" },
{ name: "Justin Bongcaron", club: "PHILADELPHIA BARBELL", weightCategory: "Male 67kg", entryTotal: "200" },
{ name: "A-jay Saint-Louis", club: "Warner University", weightCategory: "Male 67kg", entryTotal: "200" },
{ name: "Taylor Lamont", club: "Unaffiliated", weightCategory: "Male 67kg", entryTotal: "206" },
{ name: "Razmig Shahvekilian", club: "Unaffiliated", weightCategory: "Male 67kg", entryTotal: "210" },
{ name: "Jayden Bernstein", club: "FSU Weightlifting", weightCategory: "Male 67kg", entryTotal: "210" },
{ name: "Nahshon Paul", club: "Mars Hill University", weightCategory: "Male 67kg", entryTotal: "219" },
{ name: "Jakobe Morgan", club: "Gator Weightlifting", weightCategory: "Male 67kg", entryTotal: "220" },
{ name: "Shreyas Sathya", club: "Keep Pulling", weightCategory: "Male 67kg", entryTotal: "220" },
{ name: "Elijah Dy", club: "Gator Weightlifting", weightCategory: "Male 67kg", entryTotal: "230" },
{ name: "Ontarriyus daton Reid", club: "Missouri Valley College Weightlifting", weightCategory: "Male 67kg", entryTotal: "230" },
{ name: "Gavin Dunkin", club: "Unaffiliated", weightCategory: "Male 73kg", entryTotal: "170" },
{ name: "Jared Schnider", club: "University of Oregon Weightlifting Club", weightCategory: "Male 73kg", entryTotal: "170" },
{ name: "Eric Chen", club: "Unaffiliated", weightCategory: "Male 73kg", entryTotal: "171" },
{ name: "Ethan Wright", club: "George Mason Olympic Weightlifting Team", weightCategory: "Male 73kg", entryTotal: "172" },
{ name: "Gonzalo Montes", club: "FSU Weightlifting", weightCategory: "Male 73kg", entryTotal: "175" },
{ name: "Jeremy Singh", club: "Iona University Weightlifting", weightCategory: "Male 73kg", entryTotal: "175" },
{ name: "Yiwen Wu", club: "Gator Weightlifting", weightCategory: "Male 73kg", entryTotal: "180" },
{ name: "Danny Kim", club: "Olympic Weightlifting Club at The Ohio State University", weightCategory: "Male 73kg", entryTotal: "180" },
{ name: "Keshav Nair", club: "George Mason Olympic Weightlifting Team", weightCategory: "Male 73kg", entryTotal: "190" },
{ name: "Jayden Son", club: "Unaffiliated", weightCategory: "Male 73kg", entryTotal: "200" },
{ name: "Michael Habib", club: "BEANTOWN BARBELL CLUB", weightCategory: "Male 73kg", entryTotal: "201" },
{ name: "Thomas Kniss", club: "LSU - Shreveport", weightCategory: "Male 73kg", entryTotal: "205" },
{ name: "Matthew Potter", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male 73kg", entryTotal: "210" },
{ name: "Matthew Castellano", club: "FSU Weightlifting", weightCategory: "Male 73kg", entryTotal: "212" },
{ name: "Alex Lambert", club: "Mars Hill University", weightCategory: "Male 73kg", entryTotal: "212" },
{ name: "Jason Nguyen", club: "Warner University", weightCategory: "Male 73kg", entryTotal: "218" },
{ name: "Ryan Padron", club: "HI PERFORMANCE ATHLETICS", weightCategory: "Male 73kg", entryTotal: "220" },
{ name: "Will Higgins", club: "Gator Weightlifting", weightCategory: "Male 73kg", entryTotal: "220" },
{ name: "Jaden Lambert", club: "Missouri Valley College Weightlifting", weightCategory: "Male 73kg", entryTotal: "220" },
{ name: "Phillip Nelson", club: "Unaffiliated", weightCategory: "Male 73kg", entryTotal: "220" },
{ name: "Marquavious Owens", club: "Mars Hill University", weightCategory: "Male 73kg", entryTotal: "221" },
{ name: "Kendrick Parideu", club: "Concordia University Weightlifting", weightCategory: "Male 73kg", entryTotal: "224" },
{ name: "Connor Chan", club: "University of Oregon Weightlifting Club", weightCategory: "Male 73kg", entryTotal: "225" },
{ name: "Nathan Tran", club: "Unaffiliated", weightCategory: "Male 73kg", entryTotal: "230" },
{ name: "Bobby Hill", club: "LINDENWOOD LIONS", weightCategory: "Male 73kg", entryTotal: "230" },
{ name: "James Woodley", club: "Unaffiliated", weightCategory: "Male 73kg", entryTotal: "235" },
{ name: "Jared Johnson", club: "Unaffiliated", weightCategory: "Male 73kg", entryTotal: "235" },
{ name: "Trevor Mummah", club: "Gator Weightlifting", weightCategory: "Male 73kg", entryTotal: "240" },
{ name: "Michael Heins", club: "Beyond The Barbell", weightCategory: "Male 73kg", entryTotal: "250" },
{ name: "Jordan McKenzie", club: "Texas A&M Aggie Weightlifting", weightCategory: "Male 73kg", entryTotal: "255" },
{ name: "Evan Fukuhara", club: "Concordia University Weightlifting", weightCategory: "Male 73kg", entryTotal: "260" },
{ name: "Nathan Gonzaga", club: "Bexar Barbell", weightCategory: "Male 73kg", entryTotal: "265" },
{ name: "Kevin Lozoya", club: "Kaizen Barbell", weightCategory: "Male 81kg", entryTotal: "175" },
{ name: "Yiliang Chen", club: "Houston Weightlifting Academy", weightCategory: "Male 81kg", entryTotal: "175" },
{ name: "Huss Fleurimont", club: "Warner University", weightCategory: "Male 81kg", entryTotal: "180" },
{ name: "Michael Crowe", club: "Olympic Weightlifting Club at The Ohio State University", weightCategory: "Male 81kg", entryTotal: "180" },
{ name: "Blake Hanfeld", club: "UW - LA CROSSE WEIGHTLIFTING CLUB", weightCategory: "Male 81kg", entryTotal: "180" },
{ name: "Jake Conti", club: "FSU Weightlifting", weightCategory: "Male 81kg", entryTotal: "182" },
{ name: "Joseph Harper", club: "Unaffiliated", weightCategory: "Male 81kg", entryTotal: "182" },
{ name: "Travis Sykes", club: "UW - LA CROSSE WEIGHTLIFTING CLUB", weightCategory: "Male 81kg", entryTotal: "182" },
{ name: "Brandon Beane", club: "HASSLE FREE BBC", weightCategory: "Male 81kg", entryTotal: "182" },
{ name: "Rohaan Saripella", club: "UNIVERSITY OF TEXAS", weightCategory: "Male 81kg", entryTotal: "185" },
{ name: "Nathan Mark", club: "Olympic Weightlifting Club at The Ohio State University", weightCategory: "Male 81kg", entryTotal: "188" },
{ name: "Evan Vassilakis", club: "Unaffiliated", weightCategory: "Male 81kg", entryTotal: "188" },
{ name: "Harrison Olan", club: "Texas A&M Aggie Weightlifting", weightCategory: "Male 81kg", entryTotal: "190" },
{ name: "Jianhao Cui", club: "BARBARIAN BARBELL CLUB", weightCategory: "Male 81kg", entryTotal: "190" },
{ name: "Adam Schwartz", club: "Kilo Barbell Club", weightCategory: "Male 81kg", entryTotal: "190" },
{ name: "Om Borkar", club: "Steadfast Barbell", weightCategory: "Male 81kg", entryTotal: "200" },
{ name: "Tri Le", club: "University of Michigan Weightlifting", weightCategory: "Male 81kg", entryTotal: "200" },
{ name: "James Goff", club: "University of Michigan Weightlifting", weightCategory: "Male 81kg", entryTotal: "200" },
{ name: "Perceval Park", club: "University of Michigan Weightlifting", weightCategory: "Male 81kg", entryTotal: "200" },
{ name: "Isaiah Love", club: "Warner University", weightCategory: "Male 81kg", entryTotal: "200" },
{ name: "Tyler Cho", club: "UCSD Weightlifting", weightCategory: "Male 81kg", entryTotal: "210" },
{ name: "Ethan Caudle", club: "Unaffiliated", weightCategory: "Male 81kg", entryTotal: "212" },
{ name: "Stanley Mason Danner", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male 81kg", entryTotal: "220" },
{ name: "Jonathan Jones", club: "UW - LA CROSSE WEIGHTLIFTING CLUB", weightCategory: "Male 81kg", entryTotal: "220" },
{ name: "Greyson DiCosmo", club: "University of Michigan Weightlifting", weightCategory: "Male 81kg", entryTotal: "220" },
{ name: "Kevin Le", club: "Lvl-up strength", weightCategory: "Male 81kg", entryTotal: "220" },
{ name: "Ethan Christian", club: "Mach10 Weightlifting Club", weightCategory: "Male 81kg", entryTotal: "225" },
{ name: "Kieven Fischer", club: "Unaffiliated", weightCategory: "Male 81kg", entryTotal: "225" },
{ name: "Dwayne Deang", club: "Unaffiliated", weightCategory: "Male 81kg", entryTotal: "230" },
{ name: "Jack Parisien", club: "Unaffiliated", weightCategory: "Male 81kg", entryTotal: "230" },
{ name: "Julian Maldonado", club: "Gator Weightlifting", weightCategory: "Male 81kg", entryTotal: "230" },
{ name: "Jaiden Garcia", club: "Bobcat Barbell", weightCategory: "Male 81kg", entryTotal: "230" },
{ name: "William Sullivan", club: "Heartland Strength", weightCategory: "Male 81kg", entryTotal: "230" },
{ name: "Zachary Carr", club: "Texas A&M Aggie Weightlifting", weightCategory: "Male 81kg", entryTotal: "231" },
{ name: "William McCormack", club: "Fit Lab - Dirty Durham Barbell", weightCategory: "Male 81kg", entryTotal: "235" },
{ name: "Marcus Sweet", club: "Concordia University Weightlifting", weightCategory: "Male 81kg", entryTotal: "250" },
{ name: "Huntley Moore", club: "Gator Weightlifting", weightCategory: "Male 81kg", entryTotal: "250" },
{ name: "Bryce Eberhardt", club: "Mars Hill University", weightCategory: "Male 81kg", entryTotal: "251" },
{ name: "Aiden Miller", club: "Heroic Barbell", weightCategory: "Male 81kg", entryTotal: "260" },
{ name: "Owen Murphy", club: "PHILADELPHIA BARBELL", weightCategory: "Male 81kg", entryTotal: "260" },
{ name: "Logan Jeune", club: "Unaffiliated", weightCategory: "Male 81kg", entryTotal: "260" },
{ name: "Blain McFarland", club: "POWER AND GRACE PERFORMANCE.", weightCategory: "Male 81kg", entryTotal: "260" },
{ name: "Cameron Lee", club: "LINDENWOOD LIONS", weightCategory: "Male 81kg", entryTotal: "265" },
{ name: "Kevin Hill", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male 81kg", entryTotal: "270" },
{ name: "Colin Manning", club: "PHILADELPHIA BARBELL", weightCategory: "Male 81kg", entryTotal: "278" },
{ name: "Jeffy Li", club: "HASSLE FREE BBC", weightCategory: "Male 81kg", entryTotal: "280" },
{ name: "Brayden Edman", club: "Oly Concepts", weightCategory: "Male 81kg", entryTotal: "285" },
{ name: "Trevor Owens", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male 81kg", entryTotal: "290" },
{ name: "Eric Zunker", club: "Houston Weightlifting Academy", weightCategory: "Male 81kg", entryTotal: "310" },
{ name: "Joseph Sowers", club: "Moran Academy", weightCategory: "Male 89kg", entryTotal: "0" },
{ name: "Giancarlo D'Agostino", club: "Providence Barbell Club", weightCategory: "Male 89kg", entryTotal: "180" },
{ name: "Ryan Ostrowski", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "182" },
{ name: "Luis Leyva", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "191" },
{ name: "Gregory Whetstone", club: "PIONEER WLC", weightCategory: "Male 89kg", entryTotal: "191" },
{ name: "Nicholas Kent", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "191" },
{ name: "Mohammed Aiman Koli", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "191" },
{ name: "Perry Lindeman", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "195" },
{ name: "Osiriz Durana", club: "Standard Strength", weightCategory: "Male 89kg", entryTotal: "200" },
{ name: "Jaxon Cooper-Sanders", club: "Team Florida Pensacola", weightCategory: "Male 89kg", entryTotal: "207" },
{ name: "Cory Nunes", club: "Butcher Barbell", weightCategory: "Male 89kg", entryTotal: "210" },
{ name: "Joseph Hoffman", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "212" },
{ name: "Kameron Anderson", club: "RUBBER CITY WEIGHTLIFTING", weightCategory: "Male 89kg", entryTotal: "213" },
{ name: "Luke Stevens", club: "Beyond The Barbell", weightCategory: "Male 89kg", entryTotal: "215" },
{ name: "Luke Bland", club: "LSU - Shreveport", weightCategory: "Male 89kg", entryTotal: "216" },
{ name: "Gavin Schwinn", club: "UVM Weightlifting Club", weightCategory: "Male 89kg", entryTotal: "216" },
{ name: "Luis Bustamante", club: "Team Thick Weightlifting", weightCategory: "Male 89kg", entryTotal: "220" },
{ name: "Aiden Haislop", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "220" },
{ name: "Charles Neilson", club: "Texas A&M Aggie Weightlifting", weightCategory: "Male 89kg", entryTotal: "225" },
{ name: "Brayden Gerhardt", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "225" },
{ name: "Kevin Diep", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "230" },
{ name: "Rafed Abbassi", club: "MURDER OF CROWS", weightCategory: "Male 89kg", entryTotal: "230" },
{ name: "Dustin Kooyers", club: "University of Michigan Weightlifting", weightCategory: "Male 89kg", entryTotal: "230" },
{ name: "Alphonse Ortega", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "230" },
{ name: "Jared Ambrosio", club: "Villain Barbell", weightCategory: "Male 89kg", entryTotal: "230" },
{ name: "Thomas Metz", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "230" },
{ name: "Kevin Li", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "233" },
{ name: "Isaiah Mitchell", club: "HASSLE FREE BBC", weightCategory: "Male 89kg", entryTotal: "233" },
{ name: "Cameron Bui", club: "Texas A&M Aggie Weightlifting", weightCategory: "Male 89kg", entryTotal: "235" },
{ name: "Kamal Rustom", club: "Mars Hill University", weightCategory: "Male 89kg", entryTotal: "235" },
{ name: "Jon Vore", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "236" },
{ name: "Maxwell Hoffman", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "238" },
{ name: "Dylan Satkunam", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "240" },
{ name: "David Banu", club: "HUMBLE BEAST WEIGHTLIFTING", weightCategory: "Male 89kg", entryTotal: "240" },
{ name: "Javan Patton", club: "Bujanda Strong", weightCategory: "Male 89kg", entryTotal: "243" },
{ name: "William Hermanson", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "245" },
{ name: "Camden Wisner", club: "Shinshengumi Weightlifting", weightCategory: "Male 89kg", entryTotal: "250" },
{ name: "Shane Pruitt", club: "LINDENWOOD LIONS", weightCategory: "Male 89kg", entryTotal: "255" },
{ name: "Keaton OConnor", club: "Bulldog Weightlifting Club", weightCategory: "Male 89kg", entryTotal: "265" },
{ name: "Nick Sanchez", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "270" },
{ name: "Calvin Lackey", club: "LINDENWOOD LIONS", weightCategory: "Male 89kg", entryTotal: "270" },
{ name: "Cody Monsevais", club: "Origin Barbell", weightCategory: "Male 89kg", entryTotal: "270" },
{ name: "Ralph Christian Pulido", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "270" },
{ name: "Zachary Chaffin", club: "UNIVERSITY OF TEXAS", weightCategory: "Male 89kg", entryTotal: "271" },
{ name: "William Prokop", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male 89kg", entryTotal: "275" },
{ name: "Nicholas Groth", club: "Gator Weightlifting", weightCategory: "Male 89kg", entryTotal: "275" },
{ name: "Ethan Latterner", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "275" },
{ name: "Michael Davidge", club: "Concordia University Weightlifting", weightCategory: "Male 89kg", entryTotal: "278" },
{ name: "Samuel Wainwright", club: "Mars Hill University", weightCategory: "Male 89kg", entryTotal: "282" },
{ name: "Jasper Luckritz", club: "Unaffiliated", weightCategory: "Male 89kg", entryTotal: "287" },
{ name: "Gabriel Aaron Pineda", club: "Missouri Valley College Weightlifting", weightCategory: "Male 96kg", entryTotal: "190" },
{ name: "Emmanuel Kesler", club: "UW - LA CROSSE WEIGHTLIFTING CLUB", weightCategory: "Male 96kg", entryTotal: "191" },
{ name: "Anton Hugo Ramirez", club: "Texas A&M Aggie Weightlifting", weightCategory: "Male 96kg", entryTotal: "195" },
{ name: "Ty Whitley", club: "Rising Tide Weightlifting", weightCategory: "Male 96kg", entryTotal: "195" },
{ name: "Owen Davis", club: "Unaffiliated", weightCategory: "Male 96kg", entryTotal: "204" },
{ name: "Jason Cullum", club: "UNIVERSITY OF TEXAS", weightCategory: "Male 96kg", entryTotal: "210" },
{ name: "Coleman Bass", club: "Unaffiliated", weightCategory: "Male 96kg", entryTotal: "220" },
{ name: "Karl Puttler", club: "UCLA Weightlifting Club", weightCategory: "Male 96kg", entryTotal: "220" },
{ name: "Benjamin Stevens", club: "Unaffiliated", weightCategory: "Male 96kg", entryTotal: "220" },
{ name: "Thomas Cahaly", club: "Unaffiliated", weightCategory: "Male 96kg", entryTotal: "221" },
{ name: "Will Fontaine", club: "FSU Weightlifting", weightCategory: "Male 96kg", entryTotal: "224" },
{ name: "Spencer Hiatt", club: "UW - LA CROSSE WEIGHTLIFTING CLUB", weightCategory: "Male 96kg", entryTotal: "225" },
{ name: "Matthew Ma", club: "Unaffiliated", weightCategory: "Male 96kg", entryTotal: "230" },
{ name: "Giovanni CASTRO-PRIDDEE", club: "Keep Pulling", weightCategory: "Male 96kg", entryTotal: "230" },
{ name: "Richard Yan", club: "University of Michigan Weightlifting", weightCategory: "Male 96kg", entryTotal: "239" },
{ name: "Nick Radovcich", club: "BARBARIAN BARBELL CLUB", weightCategory: "Male 96kg", entryTotal: "240" },
{ name: "Marcus Boone", club: "Unaffiliated", weightCategory: "Male 96kg", entryTotal: "240" },
{ name: "Donovan Agelvis", club: "Warner University", weightCategory: "Male 96kg", entryTotal: "245" },
{ name: "Blake Stewart", club: "PIONEER WLC", weightCategory: "Male 96kg", entryTotal: "255" },
{ name: "Connor Lacey", club: "Unaffiliated", weightCategory: "Male 96kg", entryTotal: "255" },
{ name: "Bryce Keeler", club: "Stonehenge Weightlifting", weightCategory: "Male 96kg", entryTotal: "260" },
{ name: "Jackson Thomas", club: "Country Strong", weightCategory: "Male 96kg", entryTotal: "266" },
{ name: "Aidan Luther", club: "True Strength Performance Weightlifting", weightCategory: "Male 96kg", entryTotal: "270" },
{ name: "Joseph Clark", club: "UNIVERSITY OF TEXAS", weightCategory: "Male 96kg", entryTotal: "271" },
{ name: "Enzo Mancini", club: "Concordia University Weightlifting", weightCategory: "Male 96kg", entryTotal: "279" },
{ name: "Alexander Erdelac", club: "HOOSIER BARBELL CLUB", weightCategory: "Male 96kg", entryTotal: "286" },
{ name: "Spencer Dent", club: "LINDENWOOD LIONS", weightCategory: "Male 96kg", entryTotal: "295" },
{ name: "Nathan Prokop", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male 96kg", entryTotal: "300" },
{ name: "Lucas Brinson", club: "BASA Weightlifting", weightCategory: "Male 96kg", entryTotal: "300" },
{ name: "Will Easley", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male 96kg", entryTotal: "320" },
{ name: "Chrisanto D'Agostino", club: "EAST COAST GOLD W/L TEAM", weightCategory: "Male 96kg", entryTotal: "348" },
{ name: "Reilly Ploplis", club: "Butcher Barbell", weightCategory: "Male 102kg", entryTotal: "203" },
{ name: "Kurt Reyden Osuyos", club: "Unaffiliated", weightCategory: "Male 102kg", entryTotal: "203" },
{ name: "Adrian Zalduondo", club: "Warner University", weightCategory: "Male 102kg", entryTotal: "205" },
{ name: "Allen Hernandez", club: "Bobcat Barbell", weightCategory: "Male 102kg", entryTotal: "215" },
{ name: "Daniel Arevalo", club: "Keep Pulling", weightCategory: "Male 102kg", entryTotal: "230" },
{ name: "William Wilkerson", club: "PHILADELPHIA BARBELL", weightCategory: "Male 102kg", entryTotal: "240" },
{ name: "Carson Johnson", club: "LINDENWOOD LIONS", weightCategory: "Male 102kg", entryTotal: "240" },
{ name: "Noah Carr", club: "Missouri Valley College Weightlifting", weightCategory: "Male 102kg", entryTotal: "250" },
{ name: "Allan Shade", club: "Unaffiliated", weightCategory: "Male 102kg", entryTotal: "265" },
{ name: "Tyler Birkla", club: "Unaffiliated", weightCategory: "Male 102kg", entryTotal: "270" },
{ name: "William Wainwright", club: "Mars Hill University", weightCategory: "Male 102kg", entryTotal: "277" },
{ name: "Austin Widmer", club: "Texas A&M Aggie Weightlifting", weightCategory: "Male 102kg", entryTotal: "280" },
{ name: "Caleb Weakland", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male 102kg", entryTotal: "310" },
{ name: "Blaine Brooks", club: "Spoon Barbell Club", weightCategory: "Male 102kg", entryTotal: "335" },
{ name: "Britton Thompson", club: "PIONEER WLC", weightCategory: "Male 109kg", entryTotal: "203" },
{ name: "Brenden Pennington", club: "Olympic Weightlifting Club at The Ohio State University", weightCategory: "Male 109kg", entryTotal: "203" },
{ name: "Brian Zhang", club: "FSU Weightlifting", weightCategory: "Male 109kg", entryTotal: "207" },
{ name: "Georgios Vassilakis", club: "Unaffiliated", weightCategory: "Male 109kg", entryTotal: "210" },
{ name: "Sean Hansen", club: "University of Oregon Weightlifting Club", weightCategory: "Male 109kg", entryTotal: "210" },
{ name: "Samuel Sissman", club: "Houston Weightlifting Academy", weightCategory: "Male 109kg", entryTotal: "220" },
{ name: "Nolan Graupmann", club: "Concordia University Weightlifting", weightCategory: "Male 109kg", entryTotal: "235" },
{ name: "Noah Taunton", club: "Unaffiliated", weightCategory: "Male 109kg", entryTotal: "245" },
{ name: "Jacob Lewis", club: "Waxman's Gym", weightCategory: "Male 109kg", entryTotal: "250" },
{ name: "Reef Gingell", club: "Keep Pulling", weightCategory: "Male 109kg", entryTotal: "260" },
{ name: "Alfred Grenon", club: "Heartland Strength", weightCategory: "Male 109kg", entryTotal: "270" },
{ name: "Alex Papale", club: "Warner University", weightCategory: "Male 109kg", entryTotal: "270" },
{ name: "Junius Fullard", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male 109kg", entryTotal: "277" },
{ name: "Eugene Yi", club: "RVA Weightlifting", weightCategory: "Male 109kg", entryTotal: "280" },
{ name: "Maurice McClain", club: "LINDENWOOD LIONS", weightCategory: "Male 109kg", entryTotal: "285" },
{ name: "Grant Reed", club: "Bobcat Barbell", weightCategory: "Male 109kg", entryTotal: "290" },
{ name: "Victor Delgado", club: "UNIVERSITY OF TEXAS", weightCategory: "Male 109kg", entryTotal: "295" },
{ name: "William Heller", club: "TEXAS BARBELL CLUB", weightCategory: "Male 109kg", entryTotal: "309" },
{ name: "James Tice", club: "LINDENWOOD LIONS", weightCategory: "Male 109kg", entryTotal: "320" },
{ name: "Jack Freeman", club: "Concordia University Weightlifting", weightCategory: "Male +109kg", entryTotal: "205" },
{ name: "Zachary Wagle", club: "Warner University", weightCategory: "Male +109kg", entryTotal: "208" },
{ name: "Anthony Kravchenko", club: "Mach 1 Barbell", weightCategory: "Male +109kg", entryTotal: "220" },
{ name: "Austin Mozeley", club: "Unaffiliated", weightCategory: "Male +109kg", entryTotal: "220" },
{ name: "Jacob Brouse", club: "Unaffiliated", weightCategory: "Male +109kg", entryTotal: "220" },
{ name: "Kody Clark", club: "Warner University", weightCategory: "Male +109kg", entryTotal: "220" },
{ name: "Adrian Hernandez", club: "Concordia University Weightlifting", weightCategory: "Male +109kg", entryTotal: "232" },
{ name: "Owen Tannehill", club: "Warner University", weightCategory: "Male +109kg", entryTotal: "240" },
{ name: "Conner Holton", club: "Texas A&M Aggie Weightlifting", weightCategory: "Male +109kg", entryTotal: "245" },
{ name: "Hayden Eugene Kilson", club: "Unaffiliated", weightCategory: "Male +109kg", entryTotal: "247" },
{ name: "Nicholas Soler", club: "Gator Weightlifting", weightCategory: "Male +109kg", entryTotal: "250" },
{ name: "Noah Jacoby", club: "Unaffiliated", weightCategory: "Male +109kg", entryTotal: "255" },
{ name: "Bradley Bingham", club: "LINDENWOOD LIONS", weightCategory: "Male +109kg", entryTotal: "275" },
{ name: "Aidan Perez", club: "STONEAGE WEIGHTLIFTING CLUB", weightCategory: "Male +109kg", entryTotal: "280" },
{ name: "Maxwell Li", club: "University of Michigan Weightlifting", weightCategory: "Male +109kg", entryTotal: "280" },
{ name: "Daniel Kozersky", club: "NEW YORK WEIGHTLIFTING ACADEMY", weightCategory: "Male +109kg", entryTotal: "290" },
{ name: "Adam Jarski", club: "Unaffiliated", weightCategory: "Male +109kg", entryTotal: "310" }
];