name: Scrape PNW WSO Championships

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch: # Allow manual triggering

env:
  TARGET_URL: 'https://usaweightlifting.sport80.com/public/events/13967/entries/20785?bl='

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps
        
      - name: Create URL file
        run: echo "$TARGET_URL" > target_url.txt
        
      - name: Run scraper
        run: node csv_scraper.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }} 
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }} 